### ISSUE TITLE
Adding style to the input file only send the last file when submitted

### ISSUE THREAD

**Issue by javicaballero** [fyneworks/multifile#78]
Hi, i want to add some class or style to the input file, but when I submit, it only send the last file.

```html
<form class="form" id="form" method="post" enctype="multipart/form-data" action="test.php">
	<label class="btn btn-info">
			 Add Pictures <i class="fas fa-plus"></i>
			 <input name="pictures[]" type="file" multiple class="multi with-preview inputFile" accept="jpg|png"/>
	</label>
	<div class="form-row mt-2 preview"></div>
	<button type="submit" class="btn btn-success float-right">Save</button>
</form>
```
```css
.inputFile {
	width: 0.1px;
	height: 0.1px;
	overflow: hidden;
	position: absolute;
}
```
Results of test.php only POST the last file
```php
C:\wamp64\www\ro\test.php:2:
array (size=1)
  'fotos_modal' => 
    array (size=5)
      'name' => 
        array (size=1)
          0 => string 'Btrfly.jpg' (length=10)
      'type' => 
        array (size=1)
          0 => string 'image/jpeg' (length=10)
      'tmp_name' => 
        array (size=1)
          0 => string 'C:\wamp64\tmp\php95AC.tmp' (length=25)
      'error' => 
        array (size=1)
          0 => int 0
      'size' => 
        array (size=1)
          0 => int 114302
```

This only happens when I select one file at a time. If I select multiple files at once, there are no issues

I think it is a problem with the clone() operation, he ignores the style or class.

Can you help me out please? Thanks!
(Sorry for my english)

![1](https://user-images.githubusercontent.com/6868879/84838381-47db4200-b008-11ea-9b19-4fee2cea9f13.png)
![2](https://user-images.githubusercontent.com/6868879/84838384-4a3d9c00-b008-11ea-9fb3-f0e13bf38bcc.png)
![3](https://user-images.githubusercontent.com/6868879/84838385-4ad63280-b008-11ea-88b0-f9c295770617.png)
![4](https://user-images.githubusercontent.com/6868879/84838386-4c9ff600-b008-11ea-9fc7-049f454fbdb0.png)

**Comment by javicaballero** [comment]
I solved using the following code

```css
.btn-file {
	position: relative;
	overflow: hidden;
	cursor: pointer;
}
.btn-file input[type=file] {
	position: absolute;
	top: 0;
	right: 0;
	min-width: 100%;
	min-height: 100%;
	font-size: 100px;
	text-align: right;
	filter: alpha(opacity=0);
	opacity: 0;
	outline: none;
	background: white;
	cursor: inherit;
	display: block;
}
```

```html
<span class="btn btn-info btn-file">
	Add Pictures <input type="file" name="files[]" multiple class="multi with-preview" accept="jpg|png"/>
</span>
```
